[package]
name = "photonio"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/photondb/photonio"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.5"
slab = "0.4"
