[package]
name = "photonio-tokio"
version = "0.0.1"
edition = "2021"
license = "MIT"
homepage = "https://photondb.io"
repository = "https://github.com/photondb/photonio"
description = "The PhotonIO runtime based on Tokio."

[dependencies]
tokio = { version = "1.21", features = ["full"] }
