[package]
name = "photonio"
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["The PhotonIO Authors"]
homepage = "https://photondb.io"
repository = "https://github.com/photondb/photonio"
description = "The PhotonIO runtime."

[features]
default = ["core"]
core = ["dep:photonio-core"]
tokio = ["dep:photonio-tokio"]

[dependencies]
photonio-core = { version = "0.0.1", path = "../photonio-core", optional = true }
photonio-tokio = { version = "0.0.1", path = "../photonio-tokio", optional = true }
photonio-macros = { version = "0.0.1", path = "../photonio-macros" }
