name: CI

on:
  push:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --tests --benches --examples --all-features

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run tests with tokio
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features tokio
    - name: Run tests with asan
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target x86_64-unknown-linux-gnu
      env:
        RUSTFLAGS: -Zsanitizer=address
    - name: Run tests with msan
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -Zbuild-std --target x86_64-unknown-linux-gnu
      env:
        RUSTFLAGS: -Zsanitizer=memory -Zsanitizer-memory-track-origins

  tests-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Run unit tests
      uses: actions-rs/cargo@v1
      with:
        command: test